baseURL = "https://jessicacranford.com/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "jessicas-theme"
canonifyURLs = true

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "plants"
    name = "Plants"
    url = "/plants/"
    weight = 2

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4
